IllegalStateException: Have not received sensor event when getDeviceStateInfoLocked is being called
1.Before calling notifyDeviceStateInfoChangedAsync(), 
mPendingState has been passed to mCommittedState in commitPendingState()
so it is expected to have an empty mPendingState at this time.

2.Don't report device state until hardware state is known.
The previous implementation of DeviceStateProviderImpl would report the
current device state as soon as a listener was registered leading to a
series of device state changes on boot as the state of the hardware
becomes known. This changes the implementation to await callbacks before
notifying the listener of a change in device state.

Bug: 260903235
Test: 1.Cycle restart device
```
while(true)
do
    adb reboot
    sleep 200
done
```
2.adb shell logcat -b all | grep "IllegalStateException"
Change-Id: I9183b424027d2f34bc9bdaf11a7edc1ca10eeadb
Signed-off-by: huyuxin <huyuxin@xiaomi.com>